import { ChildProcess, spawn } from 'child_process'
import fs from 'fs'
import path from 'path'

export type ComfyRuntimeState = 'not_configured' | 'starting' | 'checking' | 'ready' | 'incompatible' | 'stopped' | 'failed'
export interface ComfyRuntimeConfig { rootPath: string; pythonPath: string; port: number; autoLaunch: boolean; sageAttention?: boolean; extraModelPathsConfig?: string; inputDirectory?: string; outputDirectory?: string; ollamaEndpoint?: string; ollamaModel?: string; ollamaAutoStart?: boolean; ollamaKeepWarm?: boolean }
export interface ComfyRuntimeStatus { state: ComfyRuntimeState; owned: boolean; pid: number | null; endpoint: string | null; version: string | null; error: string | null; diagnostics: string[] }
export interface ComfyRuntimeDependencies { getConfig: () => ComfyRuntimeConfig; saveConfig: (config: ComfyRuntimeConfig) => void; getBackend: () => { url: string | null; token: string | null }; spawn?: typeof spawn }
const defaults: ComfyRuntimeConfig = { rootPath: '', pythonPath: '', port: 8188, autoLaunch: false, ollamaEndpoint: 'http://127.0.0.1:11434', ollamaModel: 'qwen3:4b', ollamaAutoStart: true, ollamaKeepWarm: true }

export class ComfyRuntimeCore {
  private managed: ChildProcess | null = null
  private status: ComfyRuntimeStatus = { state: 'not_configured', owned: false, pid: null, endpoint: null, version: null, error: null, diagnostics: [] }
  private readonly deps: ComfyRuntimeDependencies
  constructor(deps: ComfyRuntimeDependencies) { this.deps = deps }
  private config() { return { ...defaults, ...this.deps.getConfig() } }
  private endpoint(c: ComfyRuntimeConfig) { return `http://127.0.0.1:${c.port}` }
  private set(next: Partial<ComfyRuntimeStatus>) { this.status = { ...this.status, ...next } }
  private validate(c: ComfyRuntimeConfig) { if (!c.rootPath || !c.pythonPath) return 'ComfyUI is not configured.'; if (!Number.isInteger(c.port) || c.port < 1 || c.port > 65535) return 'ComfyUI port must be between 1 and 65535.'; if (!fs.existsSync(path.join(c.rootPath, 'main.py'))) return 'Configured ComfyUI main.py was not found.'; if (!fs.existsSync(c.pythonPath)) return 'Configured ComfyUI Python executable was not found.'; return null }
  private async probe(c: ComfyRuntimeConfig): Promise<ComfyRuntimeStatus> { const backend = this.deps.getBackend(); if (!backend.url) return { ...this.status, state: 'checking', endpoint: this.endpoint(c), error: 'H3 local backend is still starting.' }; try { const r = await fetch(`${backend.url}/api/comfyui/minimax-h3/status?base_url=${encodeURIComponent(this.endpoint(c))}`, { headers: backend.token ? { Authorization: `Bearer ${backend.token}` } : {} }); const b = await r.json() as { status: string; comfyui_version?: string; errors?: string[]; workflow_contract_valid?: boolean }; const bad = b.status !== 'connected' || !b.workflow_contract_valid; return { state: bad ? (b.status === 'unavailable' ? 'stopped' : 'incompatible') : 'ready', owned: this.managed !== null, pid: this.managed?.pid ?? null, endpoint: this.endpoint(c), version: b.comfyui_version ?? null, error: b.errors?.[0] ?? null, diagnostics: b.errors?.slice(0,4) ?? [] } } catch { return { ...this.status, state: this.managed ? 'failed' : 'stopped', endpoint: this.endpoint(c), error: 'ComfyUI readiness check failed.', diagnostics: ['ComfyUI readiness check failed.'] } } }
  getConfig() { return this.config() }
  saveConfig(c: ComfyRuntimeConfig) { this.deps.saveConfig(c); this.set({ state: c.rootPath ? 'stopped':'not_configured', error:null, diagnostics:[] }); return c }
  async getStatus() { const c=this.config(), e=this.validate(c); return e ? { ...this.status, state:c.rootPath?'failed':'not_configured', error:e } : this.probe(c) }
  async start() { const c=this.config(), e=this.validate(c); if(e){this.set({state:c.rootPath?'failed':'not_configured',error:e});return this.status}; const now=await this.probe(c); if(now.state==='ready'||now.state==='incompatible'){this.set({...now,owned:false});return this.status}; const args=this.launchArgs(), tail=(items:string[],text:string)=>{items.push(text);return items.join('').slice(-4000)}, stdout:string[]=[], stderr:string[]=[]; this.set({state:'starting',owned:false,pid:null,endpoint:this.endpoint(c),error:null,diagnostics:['Launching local ComfyUI.']}); const child=(this.deps.spawn??spawn)(c.pythonPath,args,{cwd:c.rootPath,env:{...process.env,PYTHONIOENCODING:'utf-8',PYTHONUTF8:'1'},windowsHide:true,stdio:['ignore','pipe','pipe']}); this.managed=child; child.stdout?.on('data',d=>tail(stdout,String(d))); child.stderr?.on('data',d=>tail(stderr,String(d))); child.once('exit',(code,signal)=>{const expected=this.status.state==='stopped';if(this.managed===child)this.managed=null;const detail=[...stderr.join('').split(/\r?\n/).filter(Boolean).slice(-6),...stdout.join('').split(/\r?\n/).filter(Boolean).slice(-3)];this.set({state:expected?'stopped':'failed',owned:false,pid:null,error:expected?null:`ComfyUI exited (${code??'unknown'}${signal?`, ${signal}`:''}).`,diagnostics:expected?[]:[`exit=${code??'unknown'} signal=${signal??'none'}`,`exe=${c.pythonPath}`,`cwd=${c.rootPath}`,...detail]})}); const end=Date.now()+90000; while(Date.now()<end){if(this.managed!==child)return this.status;this.set({state:'checking',owned:true,pid:child.pid??null});const s=await this.probe(c);if(s.state==='ready'){this.set({...s,owned:true,pid:child.pid??null});return this.status};await new Promise(r=>setTimeout(r,1000))};if(this.managed===child)this.stop();this.set({state:'failed',error:'ComfyUI did not become compatible before the readiness timeout.'});return this.status }
  stop(){if(!this.managed)return {...this.status,error:'Only an H3 Director-owned ComfyUI process can be stopped.'};this.set({state:'stopped'});this.managed.kill();return this.status}
  async restart(){if(!this.managed)return {...this.status,error:'Only an H3 Director-owned ComfyUI process can be restarted.'};this.stop();await new Promise(r=>setTimeout(r,500));return this.start()}
  shutdown(){if(this.managed){this.set({state:'stopped'});this.managed.kill()}}
  launchArgs(){const c=this.config();const args=['-s','main.py','--listen','127.0.0.1','--port',String(c.port),'--feature-flag','enable_telemetry=false','--feature-flag','show_signin_button=false'];if(c.sageAttention)args.push('--use-sage-attention');if(c.extraModelPathsConfig)args.push('--extra-model-paths-config',c.extraModelPathsConfig);if(c.inputDirectory)args.push('--input-directory',c.inputDirectory);if(c.outputDirectory)args.push('--output-directory',c.outputDirectory);return args}
}
