import type { H3AspectRatio, H3ResolutionMegapixels, H3WorkflowMode, H3WorkflowProfileId } from './h3-projects'

export interface H3ModelManifestEntry { id: string; displayName: string; role: 'diffusion_model' | 'text_encoder' | 'vae' | 'audio_encoder' | 'lora' | 'other'; expectedFilename: string | null; destinationCategory: string | null; required: boolean; source: null; downloadUrl: null; sha256: null }
export interface H3WorkflowModeProfile { id: H3WorkflowMode; label: string; verified: boolean; capabilities: { imageToVideo: boolean; textToVideo: boolean; continuePrevious: boolean; multiShot: boolean; audio: boolean; referenceImage: boolean }; aspectRatios: readonly H3AspectRatio[]; resolutionMegapixels: readonly H3ResolutionMegapixels[]; fpsPresets: readonly number[]; seed: boolean; referenceFit: boolean; audioGuidance: boolean; nativePromptEnhance: boolean; postProcessing: readonly string[] }
export interface H3WorkflowProfile { id: H3WorkflowProfileId; label: string; displayName: string; providerFamily: string; version: string; profileSchemaVersion: 1; status: 'verified' | 'runtime_verified' | 'contract_verified' | 'missing_models' | 'missing_nodes' | 'incompatible' | 'not_verified'; reason?: string; modes: readonly H3WorkflowModeProfile[]; requiredModels: readonly H3ModelManifestEntry[]; apiWorkflow: string; requiredNodes: readonly string[] }

export const LTX_2_5_OFFICIAL_MODEL_PAGE = 'https://huggingface.co/Lightricks/LTX-2.5'
export const LTX_2_5_MODEL_MANIFEST: readonly H3ModelManifestEntry[] = [
  { id: 'ltx-2-5-distilled-transformer', displayName: 'Distilled transformer', role: 'diffusion_model', expectedFilename: 'ltx-2.5-22b-distilled-transformer-comfy-int8-convrot.safetensors', destinationCategory: 'diffusion_models', required: true, source: null, downloadUrl: null, sha256: null },
  { id: 'ltx-2-5-gemma-projector', displayName: 'Gemma 4 text encoder + projection', role: 'text_encoder', expectedFilename: 'gemma4-12b-with-proj-ltx-2.5-comfy-int8-convrot.safetensors', destinationCategory: 'text_encoders', required: true, source: null, downloadUrl: null, sha256: null },
  { id: 'ltx-2-5-gemma-enhancer', displayName: 'Gemma 4 prompt encoder', role: 'text_encoder', expectedFilename: 'gemma4_e2b_it_bf16.safetensors', destinationCategory: 'text_encoders', required: true, source: null, downloadUrl: null, sha256: null },
  { id: 'ltx-2-5-video-vae', displayName: 'Video VAE', role: 'vae', expectedFilename: 'ltx-2.5-video-vae-bf16.safetensors', destinationCategory: 'vae', required: true, source: null, downloadUrl: null, sha256: null },
  { id: 'ltx-2-5-audio-vae', displayName: 'Audio VAE', role: 'vae', expectedFilename: 'ltx-2.5-audio-vae-bf16.safetensors', destinationCategory: 'vae', required: true, source: null, downloadUrl: null, sha256: null },
  { id: 'ltx-2-5-spatial-upscaler', displayName: 'Spatial upscaler ×2', role: 'other', expectedFilename: 'ltx-2.5-latent-spatial-upscaler-x2-bf16-1.0.safetensors', destinationCategory: 'latent_upscale_models', required: true, source: null, downloadUrl: null, sha256: null },
]

export const H3_WORKFLOW_PROFILES: readonly H3WorkflowProfile[] = [{
  id: 'minimax_h3_image_to_video', label: 'Image-to-Video', displayName: 'MiniMax H3', providerFamily: 'MiniMax H3', version: '1', profileSchemaVersion: 1, status: 'verified', apiWorkflow: 'workflows/minimax_h3_single_scene_api.json',
  requiredNodes: ['CLIPLoader', 'LoadImage', 'ResolutionSelector', 'SaveVideo'],
  modes: [{ id: 'image_to_video', label: 'Image to Video', verified: true, capabilities: { imageToVideo: true, textToVideo: false, continuePrevious: true, multiShot: false, audio: true, referenceImage: true }, aspectRatios: ['1:1 (Square)', '16:9 (Widescreen)', '9:16 (Portrait Widescreen)'], resolutionMegapixels: [0.4, 0.6, 0.8, 1], fpsPresets: [24], seed: true, referenceFit: true, audioGuidance: true, nativePromptEnhance: false, postProcessing: ['nvidia_rtx_vsr'] }],
  requiredModels: [
    { id: 'minimax-h3-video-vae', displayName: 'Video VAE', role: 'vae', expectedFilename: 'minimax_h3_video_vae_fp16.safetensors', destinationCategory: 'vae', required: true, source: null, downloadUrl: null, sha256: null },
    { id: 'minimax-h3-audio-vae', displayName: 'Audio VAE', role: 'vae', expectedFilename: 'minimax_h3_audio_vae_fp32.safetensors', destinationCategory: 'vae', required: true, source: null, downloadUrl: null, sha256: null },
    { id: 'minimax-h3-diffusion', displayName: 'Diffusion model', role: 'diffusion_model', expectedFilename: 'minimax_h3_fl2va_pruned_int8_convrot.safetensors', destinationCategory: 'diffusion_models', required: true, source: null, downloadUrl: null, sha256: null },
    { id: 'minimax-h3-text-encoder', displayName: 'Text encoder', role: 'text_encoder', expectedFilename: 'qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors', destinationCategory: 'text_encoders', required: true, source: null, downloadUrl: null, sha256: null },
  ],
},
{
  id: 'minimax_h3_no_reference', label: 'Prompt Only', displayName: 'MiniMax H3', providerFamily: 'MiniMax H3', version: '1', profileSchemaVersion: 1, status: 'runtime_verified', reason: 'Verified through H3 Director with MiniMaxH3ImageToVideo and optional image inputs omitted: 1:1 / 640×640 / 24 FPS / 5 seconds / 124 frames with audio. This does not establish a separate MiniMax text-to-video model.', apiWorkflow: 'workflows/minimax_h3_no_reference_api.json',
  requiredNodes: ['BasicGuider', 'BasicScheduler', 'CLIPLoader', 'ComfyMathExpression', 'CreateVideo', 'KSamplerSelect', 'MiniMaxH3ImageToVideo', 'RandomNoise', 'ResolutionSelector', 'SamplerCustomAdvanced', 'SaveVideo', 'UNETLoader', 'VAEDecode', 'VAEDecodeAudio', 'VAELoader'],
  modes: [{ id: 'text_to_video', label: 'Prompt Only', verified: true, capabilities: { imageToVideo: false, textToVideo: true, continuePrevious: false, multiShot: false, audio: true, referenceImage: false }, aspectRatios: ['1:1 (Square)'], resolutionMegapixels: [0.4], fpsPresets: [24], seed: true, referenceFit: false, audioGuidance: true, nativePromptEnhance: false, postProcessing: [] }],
  requiredModels: [
    { id: 'minimax-h3-video-vae', displayName: 'Video VAE', role: 'vae', expectedFilename: 'minimax_h3_video_vae_fp16.safetensors', destinationCategory: 'vae', required: true, source: null, downloadUrl: null, sha256: null },
    { id: 'minimax-h3-audio-vae', displayName: 'Audio VAE', role: 'vae', expectedFilename: 'minimax_h3_audio_vae_fp32.safetensors', destinationCategory: 'vae', required: true, source: null, downloadUrl: null, sha256: null },
    { id: 'minimax-h3-diffusion', displayName: 'Diffusion model', role: 'diffusion_model', expectedFilename: 'minimax_h3_fl2va_pruned_int8_convrot.safetensors', destinationCategory: 'diffusion_models', required: true, source: null, downloadUrl: null, sha256: null },
    { id: 'minimax-h3-text-encoder', displayName: 'Text encoder', role: 'text_encoder', expectedFilename: 'qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors', destinationCategory: 'text_encoders', required: true, source: null, downloadUrl: null, sha256: null },
  ],
},
{
  id: 'ltx_2_5_text_to_video', label: 'Text-to-Video', displayName: 'LTX 2.5', providerFamily: 'Lightricks LTX', version: '2.5', profileSchemaVersion: 1, status: 'runtime_verified', reason: 'Verified through H3 Director for the official API export only: 16:9 / 0.9 MP / 1280×704 / 24 FPS / 5 seconds / 121 frames, native Prompt Enhance on, with synchronized audio.', apiWorkflow: 'workflows/ltx_2_5_text_to_video_api_official.json', requiredNodes: ['CLIPLoader', 'CLIPTextEncode', 'ComfyMathExpression', 'ComfySwitchNode', 'CreateVideo', 'EmptyLTXVLatentVideo', 'KSamplerSelect', 'LatentUpscaleModelLoader', 'LTXVAudioVAEDecode', 'LTXVConcatAVLatent', 'LTXVConditioning', 'LTXVDualCFGGuider', 'LTXVEmptyLatentAudio', 'LTXVLatentUpsampler', 'LTXVSeparateAVLatent', 'ManualSigmas', 'PrimitiveBoolean', 'PrimitiveInt', 'PrimitiveStringMultiline', 'RandomNoise', 'ResolutionSelector', 'SamplerCustomAdvanced', 'SaveVideo', 'TextGenerateLTX2Prompt', 'UNETLoader', 'VAEDecodeTiled', 'VAELoader'],
  modes: [{ id: 'text_to_video', label: 'Text to Video', verified: true, capabilities: { imageToVideo: false, textToVideo: true, continuePrevious: false, multiShot: false, audio: true, referenceImage: false }, aspectRatios: ['16:9 (Widescreen)'], resolutionMegapixels: [0.9], fpsPresets: [24], seed: true, referenceFit: false, audioGuidance: false, nativePromptEnhance: true, postProcessing: ['ltx_native_latent_upscale_x2', 'nvidia_rtx_vsr'] }],
  requiredModels: LTX_2_5_MODEL_MANIFEST,
},
{
  id: 'ltx_2_5_image_to_video', label: 'Image-to-Video', displayName: 'LTX 2.5', providerFamily: 'Lightricks LTX', version: '2.5', profileSchemaVersion: 1, status: 'verified', reason: 'H3-originated local I2V output is verified only for the captured distilled INT8 template on RTX 5060 Ti 16 GB: 16:9, 0.9 MP, 1280×704 output, 24 FPS, 5 seconds / 121 frames, native prompt enhancement on.', apiWorkflow: 'workflows/ltx_2_5_image_to_video_api.json', requiredNodes: ['CLIPLoader', 'CLIPTextEncode', 'ComfyMathExpression', 'ComfySwitchNode', 'CreateVideo', 'EmptyLTXVLatentVideo', 'KSamplerSelect', 'LatentUpscaleModelLoader', 'LoadImage', 'LTXVAudioVAEDecode', 'LTXVConcatAVLatent', 'LTXVConditioning', 'LTXVDualCFGGuider', 'LTXVEmptyLatentAudio', 'LTXVImgToVideoInplace', 'LTXVLatentUpsampler', 'LTXVPreprocess', 'LTXVSeparateAVLatent', 'ManualSigmas', 'PrimitiveBoolean', 'PrimitiveInt', 'PrimitiveStringMultiline', 'RandomNoise', 'ResizeImageMaskNode', 'ResolutionSelector', 'SamplerCustomAdvanced', 'SaveVideo', 'TextGenerateLTX2Prompt', 'UNETLoader', 'VAEDecodeTiled', 'VAELoader'],
  modes: [{ id: 'image_to_video', label: 'Image to Video', verified: true, capabilities: { imageToVideo: true, textToVideo: false, continuePrevious: false, multiShot: false, audio: true, referenceImage: true }, aspectRatios: ['16:9 (Widescreen)'], resolutionMegapixels: [0.9], fpsPresets: [24], seed: true, referenceFit: false, audioGuidance: false, nativePromptEnhance: true, postProcessing: ['ltx_native_latent_upscale_x2', 'nvidia_rtx_vsr'] }],
  requiredModels: LTX_2_5_MODEL_MANIFEST,
}]

export const workflowProfileRegistry = { list: () => H3_WORKFLOW_PROFILES, get: (id: H3WorkflowProfileId) => H3_WORKFLOW_PROFILES.find(profile => profile.id === id) ?? null, mode: (profileId: H3WorkflowProfileId, mode: H3WorkflowMode) => H3_WORKFLOW_PROFILES.find(profile => profile.id === profileId)?.modes.find(item => item.id === mode) ?? null }
export function modelManifestStatus(profile: H3WorkflowProfile, installedFilenames: ReadonlySet<string>): { ready: boolean; missing: string[] } { const missing = profile.requiredModels.filter(model => model.required && model.expectedFilename && !installedFilenames.has(model.expectedFilename)).map(model => model.expectedFilename!); return { ready: (profile.status === 'verified' || profile.status === 'runtime_verified') && missing.length === 0, missing } }
